### ISSUE TITLE
audio issue 

### ISSUE THREAD

**Issue by rinedogg** [jdarthur/trivia#47]
audio stops when anyone submits an answer and makes you restart. fix please

**Comment by Aljosyo** [comment]
This bug is mildly infuriating

**Comment by jdarthur** [comment]
Similar behavior when you have the image viewer open and someone sends in an answer. It’s probably the same bug because I’m re-rendering the `Question` component when a new answer comes in. 

Should be easy enough to fix if so. 

Thank you to the BortTrivia.com community for writing this up

**Comment by jdarthur** [comment]
fixed here https://github.com/jdarthur/trivia/pull/48
